[package]
name = "caper"
version = "0.0.0"
build = "build.rs"

[[bin]]
name = "caper"
doc = false

[dependencies]
cgmath = "0.15.0"
gl = "0.6.3"
glutin = "0.10.0"
png = "0.11.0"
rand = "0.3.17"
time = "0.1.38"
